#!/usr/bin/env bash
# Displays "To infinity and beyond indefinitely" with sleep 2 between each iteration

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
