#!/usr/bin/env bash
#Display numbers from 1 to 20
# 4th iteration - "bad luck from China"
# 9th iteration - "bad luck from Japan"
# 17th iteration - "bad luck from Italy"

count=1

while [ $count -le 20 ]
do 
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
 		"9") echo "bad luck from Japan";;
	 	"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
